# Site settings
title: Ryan Adkins
email: ryanadkins@gmail.com
description: 
  Personal website of Ryan Adkins.
url: "http://www.ryanadkins.com" # the base hostname & protocol for your site - used for feed.xml
github_username:  ryanadkins

# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "gulpfile.js"
  - "Gemfile"
  - "Gemfile.lock"